package de.notEOF.dispatch.enumeration;

public enum DispatchTag {

    REQ_SERVICE, //
    RESP_SERVICE,

    REQ_CLIENT_IS_DISPATCHER,
    RESP_CLIENT_IS_DISPATCHER,

    REQ_SERVICE_TYPE,
    RESP_SERVICE_TYPE,

    REQ_SERVICE_AVAILABLE,
    RESP_SERVICE_AVAILABLE,

    REQ_IP,
    RESP_IP,
    REQ_PORT,
    RESP_PORT,

    RESULT_DISPATCHING_NOT_SUPPORTED,
    RESULT_MAX_NUMBER_CLIENTS_EXCEEDED,
    RESULT_SERVICE_TYPE_UNKNOWN,
    RESULT_SERVICE_AVAILABLE,

    INFO_CLIENT_IS_DISPATCHER,
    INFO_CLIENT_IS_NO_DISPATCHER,
    INFO_UNKNOWN_MSG;
}
