package de.happtick.configuration.enumeration;

public enum HapptickConfigTag {

    REQ_ALL_APPLICATION_CONFIGURATIONS, //
    RESP_ALL_APPLICATION_CONFIGURATIONS,

    REQ_ALL_CHAIN_CONFIGURATIONS,
    RESP_ALL_CHAIN_CONFIGURATIONS,

    REQ_ALL_EVENT_CONFIGURATIONS,
    RESP_ALL_EVENT_CONFIGURATIONS,

    REQ_ALL_RAISE_CONFIGURATIONS,
    RESP_ALL_RAISE_CONFIGURATIONS,

    REQ_NEXT_APPLICATION_CONFIGURATION,
    RESP_NEXT_APPLICATION_CONFIGURATION,

    REQ_NEXT_CHAIN_CONFIGURATION,
    RESP_NEXT_CHAIN_CONFIGURATION,

    REQ_NEXT_EVENT_CONFIGURATION,
    RESP_NEXT_EVENT_CONFIGURATION,

    REQ_NEXT_RAISE_CONFIGURATION,
    RESP_NEXT_RAISE_CONFIGURATION,

    INFO_OK,
    INFO_NO_CONFIGURATION;
}
