package de.happtick.core.enumeration;

public enum ApplicationTag {

    PROCESS_APPLICATION_ID, //
    PROCESS_START_ID,
    PROCESS_START_ALLOWANCE,
    PROCESS_STOP_WORK,
    PROCESS_START_WORK,

    REQ_APPLICATION_ID,
    RESP_APPLICATION_ID,

    REQ_CLIENT_NET_ID,
    RESP_CLIENT_NET_ID,

    REQ_START_ID,
    RESP_START_ID,

    REQ_START_ALLOWED,
    RESP_START_ALLOWED,
    REQ_EXIT_CODE,
    RESP_EXIT_CODE,

    INFO_TRUE,
    INFO_FALSE,

    REQ_SAMPLE_TAG,
    RESP_SAMPLE_TAG;

}
