package de.notEOF.client.application;

public enum ApplicationTag {
    REQ_CONNECT_INSTANCE_NAME(),
    RESP_CONNECT_INSTANCE_NAME(),
    REQ_CONNECT_APPLICATION_NAME(),
    RESP_CONNECT_APPLICATION_NAME(),
    REQ_CONNECT_ADDITIONAL_NAME(),
    RESP_CONNECT_ADDITIONAL_NAME(),
    REQ_START_CLEARANCE(),
    RESP_START_CLEARANCE();

}
